// GENERATED by scripts/sync-sites.mjs — do not edit. Source: packages/*.
/**
 * @sourcedhq/log — the transparency log.
 *
 * Every verdict batch is appended to a hash chain: each record commits to the
 * previous record's hash (Certificate-Transparency style). Publish the chain
 * head anywhere public (a git commit, OpenTimestamps) and the entire history
 * up to that point becomes tamper-evident: rewriting ANY past verdict changes
 * every subsequent hash, including the anchored head.
 *
 * This is what makes "we have issued honest verdicts since day one" a
 * VERIFIABLE claim instead of a marketing line. Code can be cloned; an
 * anchored history cannot.
 *
 * Only dependency: node:crypto (SHA-256).
 */
import { createHash } from "node:crypto";
function sha256(s) {
    return createHash("sha256").update(s, "utf8").digest("hex");
}
/**
 * Canonical JSON: object keys sorted recursively, so the same payload always
 * hashes identically regardless of construction order.
 */
export function canonicalize(value) {
    return JSON.stringify(sortKeys(value));
}
function sortKeys(v) {
    if (Array.isArray(v))
        return v.map(sortKeys);
    if (v && typeof v === "object") {
        const out = {};
        for (const k of Object.keys(v).sort()) {
            out[k] = sortKeys(v[k]);
        }
        return out;
    }
    return v;
}
export function hashPayload(payload) {
    return sha256(canonicalize(payload));
}
function recordHash(seq, ts, payloadHash, prevHash) {
    return sha256(`${seq}|${ts}|${payloadHash}|${prevHash}`);
}
/**
 * Append a payload (e.g. a verdict batch) to the chain. Returns the new
 * record; the chain array is not mutated — append is `[...chain, record]`
 * at the call site, or use the returned record with your own storage.
 */
export function append(chain, payload, ts) {
    const seq = chain.length;
    const prevHash = seq === 0 ? "" : chain[seq - 1].hash;
    const payloadHash = hashPayload(payload);
    return { seq, ts, payloadHash, prevHash, hash: recordHash(seq, ts, payloadHash, prevHash) };
}
/** The chain head — the one hash to anchor publicly. */
export function head(chain) {
    return chain.length === 0 ? null : chain[chain.length - 1].hash;
}
/**
 * Verify the whole chain: every record's hash must recompute, every link must
 * point at its predecessor, sequence numbers must be contiguous.
 */
export function verify(chain) {
    for (let i = 0; i < chain.length; i++) {
        const r = chain[i];
        if (r.seq !== i)
            return { ok: false, badIndex: i, reason: "sequence gap" };
        const expectedPrev = i === 0 ? "" : chain[i - 1].hash;
        if (r.prevHash !== expectedPrev)
            return { ok: false, badIndex: i, reason: "broken link" };
        if (recordHash(r.seq, r.ts, r.payloadHash, r.prevHash) !== r.hash) {
            return { ok: false, badIndex: i, reason: "hash mismatch" };
        }
    }
    return { ok: true, length: chain.length, head: head(chain) ?? "" };
}
/**
 * Verify that a specific payload is the one committed at position `seq`.
 * Together with a verified chain + anchored head, this proves the payload
 * existed unmodified when the head was anchored.
 */
export function verifyPayloadAt(chain, seq, payload) {
    const r = chain[seq];
    if (!r)
        return false;
    return r.payloadHash === hashPayload(payload);
}
//# sourceMappingURL=index.js.map