// GENERATED by scripts/sync-sites.mjs — do not edit. Source: packages/*.
/**
 * @sourced/core — the corroboration primitive.
 *
 * Given a stream of claims from many origins, Sourced tells you how many
 * INDEPENDENT sources corroborate each one, since when, and hands you the
 * receipts. It says "confirmed by sources" — never "the truth".
 *
 * Zero runtime dependencies. Storage, clustering, clock and config are
 * injected. Fail-open by contract (G7): `assess` never throws into the
 * stream it annotates — on any failure claims pass through unlabeled.
 *
 * The honesty guarantees (G1–G7) live in the spec and are enforced by
 * @sourced/conformance. The default config values ARE the contract: they
 * encode the undercount-never-overcount tuning. Loosening them is a
 * conscious act, not a knob to fiddle.
 */
// Stopwords (EN + DE) — carry no event identity.
const STOP = new Set([
    "the", "a", "an", "and", "or", "but", "of", "to", "in", "on", "at", "for",
    "with", "as", "by", "from", "into", "over", "after", "before", "is", "are",
    "was", "were", "be", "been", "has", "have", "had", "will", "would", "can",
    "could", "new", "says", "say", "said", "amid", "its", "his", "her", "their",
    "der", "die", "das", "und", "oder", "von", "zu", "im", "auf", "mit",
    "für", "den", "dem", "des", "ein", "eine", "ist", "sind", "war", "wird",
    "nach", "vor", "über", "als", "sich", "auch", "bei", "aus", "wie", "mehr",
]);
/**
 * The default tuning IS the honesty contract (undercount, never overcount).
 */
export const DEFAULT_CONFIG = {
    mergeSimilarity: 0.6,
    minSharedTokens: 3,
    confirmedAt: 4,
    corroboratedAt: 2,
    breakingWindowMs: 30 * 60 * 1000,
    eventTtlMs: 36 * 60 * 60 * 1000,
    maxEvents: 400,
    receiptsCap: 6,
    keyTokens: 8,
    stopwords: STOP,
};
// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------
/** Title → meaning-bearing tokens (lowercased, no stopwords, ≥3 chars). */
export function tokenize(title, stopwords = STOP) {
    return title
        .toLowerCase()
        .replace(/[^a-z0-9äöüéèàçß\s]/gi, " ")
        .split(/\s+/)
        .filter((t) => t.length >= 3 && !stopwords.has(t));
}
/** Deterministic event key: sorted top tokens. */
export function keyOf(tokens, keyTokens = DEFAULT_CONFIG.keyTokens) {
    return Array.from(new Set(tokens)).sort().slice(0, keyTokens).join(" ");
}
function sharedCount(a, b) {
    let n = 0;
    for (const t of a)
        if (b.has(t))
            n++;
    return n;
}
function jaccard(a, b) {
    if (a.size === 0 || b.size === 0)
        return 0;
    const inter = sharedCount(a, b);
    return inter / (a.size + b.size - inter);
}
// ---------------------------------------------------------------------------
// The primitive
// ---------------------------------------------------------------------------
/**
 * Annotate a batch of claims with corroboration verdicts and fold them into
 * the persistent event store.
 *
 * Returns one entry per input claim, in order. `null` means "unassessable"
 * (e.g. a title with no meaning-bearing tokens) — the claim simply passes
 * through unlabeled. On ANY internal failure the whole batch degrades to
 * unlabeled instead of throwing (G7).
 */
export async function assess(claims, options = {}) {
    try {
        return await assessInner(claims, options);
    }
    catch {
        // G7 — fail open, never break the stream we annotate.
        return claims.map(() => null);
    }
}
async function assessInner(claims, options) {
    const cfg = { ...DEFAULT_CONFIG, ...options.config };
    const now = options.now ?? Date.now();
    const clustersOf = (id) => {
        const c = options.clusters;
        if (!c)
            return undefined;
        return c instanceof Map ? c.get(id) : c[id];
    };
    // Load the working set — best-effort (G7).
    let store = {};
    if (options.store) {
        try {
            store = (await options.store.load()) ?? {};
        }
        catch {
            store = {};
        }
    }
    // Retire expired events out of the working set — into the archive, not
    // into oblivion: the history is the moat.
    const retired = [];
    for (const k of Object.keys(store)) {
        if (now - store[k].lastSeenAt > cfg.eventTtlMs) {
            retired.push(store[k]);
            delete store[k];
        }
    }
    // Token sets of known events, for similarity matching.
    const known = Object.values(store).map((e) => ({
        ev: e,
        tokens: new Set(tokenize(e.title, cfg.stopwords)),
    }));
    const verdicts = [];
    for (const claim of claims) {
        const tokens = tokenize(String(claim?.title ?? ""), cfg.stopwords);
        if (tokens.length === 0) {
            verdicts.push(null);
            continue;
        }
        const tokenSet = new Set(tokens);
        // Origins reporting this event IN THIS BATCH (from the injected
        // clustering; no cluster → a lone report → just its own origin).
        const batchOrigins = clustersOf(claim.id) ?? [claim.origin];
        // Find the matching event: exact key first, then the dual gate (G1) —
        // high similarity AND enough shared meaning tokens. Both must hold.
        const k = keyOf(tokens, cfg.keyTokens);
        let match = store[k];
        if (!match) {
            let best = null;
            for (const { ev, tokens: et } of known) {
                const sim = jaccard(tokenSet, et);
                if (sim >= cfg.mergeSimilarity &&
                    sharedCount(tokenSet, et) >= cfg.minSharedTokens &&
                    (!best || sim > best.sim)) {
                    best = { ev, sim };
                }
            }
            match = best?.ev;
        }
        let ev;
        if (match) {
            ev = match;
            // Independence is by origin (G3): a Set collapses syndication.
            ev.origins = Array.from(new Set([...ev.origins, ...batchOrigins]));
            ev.title = claim.title; // adopt the freshest wording
            ev.lastSeenAt = now;
        }
        else {
            ev = {
                key: k,
                title: claim.title,
                origins: Array.from(new Set(batchOrigins)),
                firstSeenAt: now,
                lastSeenAt: now,
            };
            store[k] = ev;
            known.push({ ev, tokens: tokenSet }); // later claims in batch can match
        }
        // Corroboration = distinct origins (this batch ∪ history).
        const corro = ev.origins.length;
        // Receipts (G4): who else — never the claim's own origin, capped.
        const receipts = corro > 1
            ? ev.origins.filter((s) => s !== claim.origin).slice(0, cfg.receiptsCap)
            : [];
        // Signal rides the RELIABLE clock (G6): the upstream publish time, never
        // our own first-seen guess — a matching error can shift a count but can
        // never invent urgency. Single origins stay bare (G5).
        const pubMs = new Date(claim.publishedAt).getTime();
        const pubAge = Number.isFinite(pubMs) ? now - pubMs : Infinity;
        let signal = null;
        if (corro >= cfg.confirmedAt)
            signal = "confirmed";
        else if (corro >= cfg.corroboratedAt && pubAge < cfg.breakingWindowMs)
            signal = "breaking";
        else if (corro >= cfg.corroboratedAt)
            signal = "developing";
        verdicts.push({
            corroboration: corro,
            corroboratingSources: receipts,
            firstSeenAt: new Date(ev.firstSeenAt).toISOString(),
            signal,
        });
    }
    // Cap the working set — evicted events retire into the archive.
    const entries = Object.entries(store).sort((a, b) => b[1].lastSeenAt - a[1].lastSeenAt);
    const capped = {};
    for (const [key, ev] of entries.slice(0, cfg.maxEvents))
        capped[key] = ev;
    for (const [, ev] of entries.slice(cfg.maxEvents))
        retired.push(ev);
    if (retired.length > 0 && options.archive) {
        try {
            await options.archive(retired);
        }
        catch {
            /* best-effort (G7) */
        }
    }
    if (options.store) {
        try {
            await options.store.save(capped);
        }
        catch {
            /* best-effort (G7) */
        }
    }
    return verdicts;
}
// ---------------------------------------------------------------------------
// Batteries: in-memory store (tests, demos, single-process use)
// ---------------------------------------------------------------------------
export function createMemoryStore(initial = {}) {
    let state = structuredClone(initial);
    return {
        load: () => structuredClone(state),
        save: (s) => {
            state = structuredClone(s);
        },
        snapshot: () => structuredClone(state),
    };
}
//# sourceMappingURL=index.js.map