/**
 * Embed the built engine into the sites as single files, so each app under
 * apps/ deploys on Vercel with ZERO build/install (static + /api functions).
 *
 *   npm run build && node scripts/sync-sites.mjs
 *
 * Generated files (committed on purpose — they make deploys build-free):
 *   apps/run/api/_core.mjs
 *   apps/network/api/_core.mjs
 *   apps/network/api/_log.mjs          (file-storage re-export stripped)
 *   apps/network/api/_conformance.mjs  (import rewritten to ./_core.mjs, badge inlined)
 *   apps/{ink,run,network}/style.css   (from shared/site.css)
 */
import { copyFileSync, cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");
const write = (p, s) => {
  mkdirSync(dirname(join(root, p)), { recursive: true });
  writeFileSync(join(root, p), s, "utf8");
  console.log("synced", p);
};

const banner = "// GENERATED by scripts/sync-sites.mjs — do not edit. Source: packages/*.\n";

const coreIndex = read("packages/core/dist/index.js");
const coreIndependence = read("packages/core/dist/independence.js");
const core = banner + coreIndependence + "\n" + coreIndex.replace(/^export \{[^}]*\} from "\.\/independence\.js";\r?\n/gm, "").replace(/^import \{[^}]*\} from "\.\/independence\.js";\r?\n/gm, "");
write("apps/run/api/_core.mjs", core);
write("apps/network/api/_core.mjs", core);
write("apps/ink/api/_core.mjs", core);

// verify/canonicalize only — drop the node:fs-backed file helpers.
const log = banner + read("packages/log/dist/index.js").replace(/^export \{[^}]*\} from "\.\/file\.js";\r?\n/m, "");
write("apps/network/api/_log.mjs", log);
write("apps/run/api/_log.mjs", log);

// conformance + badge inlined (badge.js is a sibling module)
const badgeCode = read("packages/conformance/dist/badge.js");
const conformanceIndex = read("packages/conformance/dist/index.js");
const conformance = banner + badgeCode + "\n" + conformanceIndex.replaceAll('"@sourcedhq/core"', '"./_core.mjs"').replace(/^export \{[^}]*\} from "\.\/badge\.js";\r?\n/m, "");
write("apps/network/api/_conformance.mjs", conformance);

for (const app of ["ink", "run", "network"]) {
  copyFileSync(join(root, "shared/site.css"), join(root, `apps/${app}/style.css`));
  copyFileSync(join(root, "shared/site.js"), join(root, `apps/${app}/site.js`));
  console.log(`synced apps/${app}/style.css + site.js`);
}

const clerkDist = join(root, "node_modules/@clerk/clerk-js/dist");
const clerkTarget = join(root, "apps/run/dashboard/clerk");
if (existsSync(clerkDist)) {
  cpSync(clerkDist, clerkTarget, { recursive: true });
  console.log("synced apps/run/dashboard/clerk/ (Clerk JS SDK)");
}
